---
title: "Einstieg"
description: |
  Einstieg
site: distill::distill_website
---

```{r, include=FALSE}
library(tidyverse)
library(fs)
library(dplyr)
library(ggplot2)
library(ggiraph)
library(plotly)
library(magick)
library(tibble)
library(cowplot)
library(png)
library(patchwork)
```

```{r, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
#Idee: geom_point und geom_line kombinieren 

Woche <- c(1, 4, 25, 52)
Gramm <- c(5,20,125,260)
Einstieg_HL <- tibble(Woche, Gramm)
```


```{r}
# plot
Einstieg_HL %>%
  ggplot(aes(Woche, Gramm)) +
   geom_line () +
  geom_point_interactive(aes(tooltip = Gramm), colour= "#00868B", size = 4) +
    scale_y_continuous(limits = c(0, 300), breaks = c(0,50,100,150,200,250,300)) +
    scale_x_continuous (limits = c(0,60), breaks= c(1, 4, 25, 52), labels = c("eine Woche", "ein Monat", "halbes Jahr", "ein Jahr")) +
  labs(title = "Wie viel Mikroplastik landet in unserem Körper?", subtitle = "Die durchschnittliche Aufnahme von Mikroplastik pro Person\ninnerhalb eines Jahres mit Referenzobjekten", x = "") +
  annotate(geom = "text", label= "Kreditkarte", x= 5.5, y= 2.5) + 
  annotate(geom= "text", label= "Zahnbürste", x= 9.2, y= 20) +
annotate(geom= "text", label= "Creme-Tube", x= 30, y= 120) +
   annotate(geom= "text", label= "Butter", x= 54.5,y= 250) +
    theme_minimal_hgrid() +
  theme(axis.text.x = element_text(angle = 30, hjust = 1)) -> EinstiegsPlot

  
# dateipfad
kreditkarte <- "icons/Kreditkarte.png"
zahnbuerste <- "icons/zahnbuerste.png"
creme <- "icons/creme.png"
butter <- "icons/Butter.png"
  
# png dateien einlesen
img1 <- readPNG(kreditkarte, native = TRUE)
img2 <- readPNG(zahnbuerste, native = TRUE)
img3 <- readPNG(creme, native = TRUE)
img4 <- readPNG(butter, native = TRUE)
  
# bilder zum plot hinzufügen  
img_graph <- EinstiegsPlot +                  
  inset_element(p = img1,
                left = 0.02,
                bottom = 0.09,
                right = 0.08,
                top = 0.3) + 
  inset_element(p = img2,
                left = 0.08,
                bottom = 0.17,
                right = 0.17,
                top = 0.3) +
  inset_element(p = img3,
                left = 0.3,
                bottom = 0.5,
                right = 0.5,
                top = 0.7) +
  inset_element(p = img4,
                left = 0.7,
                bottom = 0.87,
                right = 0.85,
                top = 0.98) 


girafe(
  ggobj = img_graph,
  width_svg = 7,
  height_svg = 7*0.618,
    options = list(
    opts_tooltip(css = "background: #F5F5F5; color: #000000;")))

```


