---
title: "Globales Plastik"
description: |
  Plastik Global
site: distill::distill_website
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

library(dplyr)
library(colorspace)
library(ggthemes)
library(psych)
library(cowplot)
library(plotly)
library(ggiraph)

```

```{r}
global_plastic <- readr::read_csv("data/global-plastics-production.csv")

global_plastic %>% rename(gpp = `Global plastics production (million tonnes)`) -> global_plastic

global_plastic %>%
 mutate(gpp = as.numeric(gpp)/1000000) %>%
ggplot(aes(x = Year, y = gpp )) + geom_line(color = '#00868B', alpha = 0.6) + geom_point_interactive(aes(data_id = gpp, tooltip = gpp), color = '#00868B') +
  scale_x_continuous(limits = c(1950, 2015), breaks = c(1950, 1960, 1970, 1980, 1990, 2000, 2010, 2015), expand = c(0.02,0.02)) +
  scale_y_continuous(limits = c(0, 400), breaks = c(0, 50, 100, 150, 200, 250, 300, 350, 400), expand = c(0,0)) +
  labs(x = "", y = "Plastik in Millionen Tonnen", title = "Im Vergleich zu 1950 hat sich 2015 die jährliche\n Plastikproduktion fast um das 200-fache erhöht", subtitle = "Globale Entwicklung der Plastikproduktion in Millionen Tonnen von 1950 bis 2015") +
  theme_minimal_hgrid(12) -> plot_global_plastic

girafe(
  ggobj = plot_global_plastic,
  width_svg = 7,
  height_svg = 7*0.618,
    options = list(
    opts_tooltip(css = "background: #00868B; color: #FFFFFF;padding:2px;border-radius:2px;")))

```

```{r}
cumulative_global_plastic <- readr::read_csv("data/cumulative-global-plastics.csv")

cumulative_global_plastic %>%
  rename(cgpp = `Cumulative global plastics production (million tonnes)`) %>%
 mutate(cgpp = as.numeric(cgpp)/1000000000) %>%
ggplot(aes(x = Year, y = cgpp )) + geom_area(fill = '#00868B', alpha= 0.6) + geom_point_interactive(aes(data_id = cgpp, tooltip = cgpp), color = '#00868B') +
  scale_x_continuous(limits = c(1950, 2015), breaks = c(1950, 1960, 1970, 1980, 1990, 2000, 2010, 2015), expand = c(0.02, 0.02)) +
  scale_y_continuous(limits = c(0, 8), breaks = c(0, 1, 2, 3, 4, 5, 6, 7, 8), expand = c(0,0)) +
  labs(x = "", y = "Plastik in Milliarden Tonnen", title = "Mehr als die Hälfte des weltweit produzierten Plastiks\n wurde in den letzten 15 Jahren* produziert", subtitle = "Kumulation  der globalen Plastikproduktion von 1950 bis 2015" ) +
  theme_minimal_hgrid(12) -> plot_cumulative_global_plastic

girafe(
  ggobj = plot_cumulative_global_plastic,
  width_svg = 7,
  height_svg = 7*0.618,
    options = list(
    opts_tooltip(css = "background: #00868B; color: #FFFF; padding:2px;border-radius:2px;")))


```

```{r}

#per_capita_plastic_waste <- readr::read_csv("data/per-capita-plastic-waste-vs-gdp-per-capita.csv")
#per_capita_mismanaged_plastic <- readr::read_csv("data/per-capita-mismanaged-plastic-waste-vs-gdp-per-capita.csv")

#Kombinieren der beiden Datensätze mit per Capita plastic waste und per capita mismanaged plastic
#combi <- inner_join(per_capita_mismanaged_plastic, per_capita_plastic_waste)

#CSV Datei wurde um die Spalte Kontinent ergänzt, gefiltert auf das Jahr 2010  und wird nun neu eingelesen
data_final<- readr::read_csv("data/data_cleaned.csv") %>%
  na.omit() -> mydata

mydata %>%
  rename(BIP = `GDP`, Kontinent = 'Continent') %>%
  mutate(`Per capita mismanaged plastic waste` = `Per capita mismanaged plastic waste`*1000) %>%
  mutate(`Per capita plastic waste (kg/person/day)` = `Per capita plastic waste (kg/person/day)`*1000) %>%
  rename(`Per capita plastic waste (g/person/day)` = `Per capita plastic waste (kg/person/day)`) %>%
  select(Entity, `Per capita mismanaged plastic waste`, `Per capita plastic waste (g/person/day)`, BIP, Kontinent) -> mydata2

#highlight_DL <- mydata2 %>%
 # filter(Entity == "Deutschland")

mydata2 %>%
  ggplot(aes(x = `Per capita plastic waste (g/person/day)`, y = `Per capita mismanaged plastic waste`, size = BIP, fill = Kontinent)) + geom_point_interactive(position = "jitter", shape = 21, color = "black", aes(data_id = Entity, tooltip = Entity)) + 
  scale_x_continuous(limits = c(0, 700), breaks = c(0, 100, 200, 300, 400, 500, 600, 700)) +
  scale_y_continuous(limits = c(0, 300), breaks = c(0, 50, 100, 150, 200, 250, 300)) +
  theme_minimal_grid() +
  theme(axis.text.y = element_text(vjust = 0)) +
  scale_fill_brewer(palette = "Set2") +
  labs(x = "Plastikmüllproduktion pro Kopf (täglich in g)", y = "Inadäquat entsorgter Plastikmüll pro Kopf (täglich in g)", title = "Problematisch ist die Mischung aus hoher Plastikproduktion in\n wohlhabenderen und inadäquater Entsorgung in ärmeren Ländern ", subtitle = "Zusammenhang von Wohlstand, Plastikmüllproduktion und inadäquater Entsorgung") +
  annotate(geom = "label", label= "Deutschland", x= 490, y= 25) -> plot_per_capita_waste_mismanagement_GDP


girafe(
  ggobj = plot_per_capita_waste_mismanagement_GDP,
  width_svg = 9,
  height_svg = 9*0.618,
    options = list(
    opts_tooltip(opacity = .7, css = "background-color:gray;color:white;padding:2px;border-radius:2px;"),
    opts_hover(css = "fill: #00868B;"),
    opts_hover_inv(css = "opacity: 0.3;")))

#Definition inadäquate Entsorgung auf Website ergänzen + Info das Daten aus 2010 sind 

```

