---
title: "About this site"
description: |
  Some additional details about the website
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

library(dplyr)
library(ggplot2)
theme_set(theme_bw())
library(devtools)
library(usethis)
library(sf)
library(rnaturalearth)
library(rnaturalearthdata)
library(ggiraph)
library(colorspace)

#install.packages(c("cowplot", "googleway", "ggplot2", "ggrepel", 
#"ggspatial", "libwgeom", "sf", "rnaturalearth", "rnaturalearthdata"))
```

```{r}
#Karte Europa (2018) > Code einfügen!!
#falls der Tooltip der name des Landes sein soll: tooltip= name!!

#Datenstze einlesen 
waste_per_country <- readr::read_csv("data/waste_2018.csv")

#Länder der Welt einlesen
world <- ne_countries(scale = "medium", returnclass = "sf")


#Länder mit dem Datensatz zusammenfügen 
world %>%
 left_join(waste_per_country, by = c("gu_a3" = "Code"),all.x=TRUE) -> world_plastic

#plastic waste per capita in Factor umwandeln 

world_plastic<-world_plastic%>%
  mutate_at(vars(Plastic_waste_annual_capita), as.numeric)

b<-c(0,10,20,30,40,50,60,70,80)
names<- c("<9", "10-19","20-29","30-39","40-49","50-59","60-69",">70")


cut(world_plastic$Plastic_waste_annual_capita, breaks =b, labels = names) -> world_plastic$Plastic_waste_annual_capita_1


#Grafik erstellen
world_plastic %>%
  ggplot() +
  aes(fill = Plastic_waste_annual_capita_1) +
  geom_sf_interactive(color = "black",
                      aes(tooltip = name)) +
  coord_sf(xlim = c(-23, 45), ylim = c(35, 70)) +
  labs(title = "So viel Plastikmüll fällt in der EU an",
       subtitle = "Plastikmüll pro Kopf in EU-ländern, 2018",
       fill = "Kg/Einwohner*in")+
  theme(plot.title = element_text(size = 20, face = "bold")) +
  theme(legend.title = element_text(size = 12), legend.text = element_text(size = 10))+
  theme_void() +
  theme(legend.position = "right") +
  scale_fill_discrete_sequential(palette = "GnBu", na.value = "grey 97", na.translate=FALSE)->plastic_map

ggiraph::girafe(
  ggobj = plastic_map,
  width_svg = 10,
  height_svg = 10 * 0.618,
  options = list(
    opts_tooltip(opacity = .9, css = "background-color:gray;color:white;padding:2px;border-radius:2px;"),
    opts_hover(css = "fill: #00868B;"),
    opts_hover_inv(css = "opacity: 0.3;")
  )
)

```



```{r}
#Weltkarte > Code einfügen!!
#Daten einlesen 

world_plastic <- readr::read_csv("data/plastic-waste-generation-total.csv")

#Daten bearbeiten
world_plastic%>%
mutate(plastic_waste_tt = `Plastic waste generation (tonnes, total)`/ 1000)-> world_plastic


#Länder der Welt einlesen
world <- ne_countries(scale = "medium", returnclass = "sf")

#Länder mit dem Datensatz zusammenfügen
world %>% 
 left_join(world_plastic, by = c("gu_a3" = "Code"), all.x=TRUE) -> world_plastic_1


world_plastic_1<-world_plastic_1%>%
  mutate_at(vars(plastic_waste_tt), as.numeric)

c<-c(0, 2000, 5000, 10000, 20000, 30000, 40000, 50000, 60000)
names_1<- c("1-2000", "2000-5000", "5000-10000", "10000-20000", "20000-30000", "30000-40000",  "40000-50000", "50000-60000")


cut(world_plastic_1$plastic_waste_tt, breaks =c, labels = names_1) -> world_plastic_1$plastic_waste_tt


world_plastic_1%>%
  ggplot()+
  aes(fill = plastic_waste_tt)+
  geom_sf_interactive(aes(tooltip = name), color= "black")+
  labs(fill="Plastikmüllproduktion in tausend Tonnen") +
  labs(title = "Deutschland produzierte 2010 ganze 14.476.561 Tonnen Plastikmüll", subtitle = "Totale Plastikmüllproduktion pro Land im Jahr 2010")+
  theme(plot.title = element_text(size = 20, face = "bold"))+
  theme_void() +
  theme(legend.position = "bottom", legend.direction = "horizontal") +
  theme(legend.title = element_text(size = 12), legend.text = element_text(size = 10))+
  scale_fill_discrete_sequential(palette = "Emrld", na.value = "grey 97", na.translate=FALSE)->plastic_map_1


ggiraph::girafe(
  ggobj = plastic_map_1, 
  pointsize = 14,
  width_svg = 10,
  height_svg = 10* 0.618,
  options = list(
    opts_tooltip(opacity = .9, css = "background-color:gray;color:white;padding:2px;border-radius:2px;"),
    opts_hover(css = "fill: #00868B;"),
    opts_hover_inv(css = "opacity: 0.3;")
  )
)


```






```{r}
# Backup 

#waste_per_country_capita <- readr::read_csv("data/plastic-waste-per-capita.csv")

#Kombinieren der beiden Datensätze mit Waste generation per country und per capita waste per country
#combi <- inner_join(waste_per_country, waste_per_country_capita)


#Kombinieren der beiden Datensätze
#combi <- inner_join(waste_per_country, waste_per_capita_2010)


#combi%>%
# rename(per_capita_kg = `Per capita plastic waste (kg/person/day)`) %>%
# mutate(per_capita_g = per_capita_kg*1000) -> combi

#world %>% 
 #left_join(combi, by = c("gu_a3" = "Code")) -> world_plastic

#world_plastic<-world_plastic%>%
  #mutate_at(vars(Plastic_waste_annual_total_t), as.numeric)


#scale_fill_continuous_sequential(
    #breaks = c(10, 20, 30, 40, 50, 60, 70),
    #labels = c("10", "20", "30", "40", "50", "60", "70"),
    #palette = "BluGrn",
    #na.value = "grey 97"
```


