---
title: "Plastik in Plots - ein Projekt von den Plottys"
description: |
  Herzlich willkommen auf unserer Website!
  Hier gibt's einiges zu sehen und zu erfahren zum Thema Plastik!
site: distill::distill_website
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
#Pakete laden

library(tidyverse)
library(fs)
library(dplyr)
library(ggplot2)
library(ggiraph)
library(plotly)
library(magick)
library(tibble)
library(cowplot)
library(png)
library(patchwork)
library(colorspace)
library(ggthemes)
library(psych)
library(readxl)
library(gganimate)

```


```{r Daten für die Visualisierungen, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

#Daten Einsteigsgrafik
Woche <- c(1, 4, 25, 52)
Gramm <- c(5,20,125,260)
Einstieg_HL <- tibble(Woche, Gramm)

#Daten Globale Entwicklung der Plastikproduktion
global_plastic <- readr::read_csv("data/global-plastics-production.csv")
global_plastic %>% rename(gpp = `Global plastics production (million tonnes)`) -> global_plastic
#Daten für Grafik zur kumulativen Entwicklung
cumulative_global_plastic <- readr::read_csv("data/cumulative-global-plastics.csv")

#Daten für Grafik Abfallaufkommen

Abfallaufkommen <- read_excel("data/Abfallaufkommen_Plastik.xlsx")
#Umbenennung
Abfallaufkommen <- Abfallaufkommen %>%
                  rename(Land = 'TIME')
#nur Deutschland
Abfallaufkommen %>%
 filter(Land ==  "Germany (until 1990 former territory of the FRG)") -> Abfallaufkommen_DE
#Umformen und fehlende Werte entfernen
Abfallaufkommen_DE %>%
pivot_longer(cols = -Land, names_to = "Jahre", values_to = "n") %>%
  na.omit() -> Plastikabfall_DE
Plastikabfall_DE$Jahre <- as.numeric(as.character(Plastikabfall_DE$Jahre))  # Convert one variable to numeric
Plastikabfall_DE$n <- as.numeric(as.character(Plastikabfall_DE$n))
Plastikabfall_DE %>%
  mutate(MillTonnen = n/1000000) %>%
  mutate(MillTonnen =  round(MillTonnen, 2))-> PlastikinMillTonnen

#Daten für Grafik Abfallmanagement
global_plastic_fate <- readr::read_csv("data/global-plastic-fate.csv")

#Daten für Plot Ländervergleich Produktion, Missmanagement und BIP
data_final<- readr::read_csv("data/data_cleaned.csv") %>%
  na.omit() -> mydata
#Data Wrangling
mydata %>%
  rename(BIP = `GDP`, Kontinent = 'Continent') %>%
  mutate(`Per capita mismanaged plastic waste` = `Per capita mismanaged plastic waste`*1000) %>%
  mutate(`Per capita plastic waste (kg/person/day)` = `Per capita plastic waste (kg/person/day)`*1000) %>%
  rename(`Per capita plastic waste (g/person/day)` = `Per capita plastic waste (kg/person/day)`) %>%
  select(Entity, `Per capita mismanaged plastic waste`, `Per capita plastic waste (g/person/day)`, BIP, Kontinent) -> mydata2
```

```{r}
# plot
Einstieg_HL %>%
  ggplot(aes(Woche, Gramm)) +
   geom_line () +
  geom_point_interactive(aes(tooltip = Gramm), colour= "#00868B", size = 4) +
    scale_y_continuous(limits = c(0, 300), breaks = c(0,50,100,150,200,250,300)) +
    scale_x_continuous (limits = c(0,60), breaks= c(1, 4, 25, 52), labels = c("eine Woche", "ein Monat", "halbes Jahr", "ein Jahr")) +
  labs(title = "Wie viel Mikroplastik landet in unserem Körper?", subtitle = "Die durchschnittliche Aufnahme von Mikroplastik pro Person\ninnerhalb eines Jahres mit Referenzobjekten", x = "") +
  annotate(geom = "text", label= "Kreditkarte", x= 5.7, y= 2.8) + 
  annotate(geom= "text", label= "Zahnbürste", x= 9.5, y= 21) +
annotate(geom= "text", label= "Creme-Tube", x= 30.5, y= 120) +
   annotate(geom= "text", label= "Butter", x= 55,y= 250) +
    theme_minimal_hgrid() +
  theme(axis.text.x = element_text(angle = 30, hjust = 1)) -> EinstiegsPlot
  
# dateipfad
kreditkarte <- "icons/Kreditkarte.png"
zahnbuerste <- "icons/zahnbuerste.png"
creme <- "icons/creme.png"
butter <- "icons/Butter.png"
  
# png dateien einlesen
img1 <- readPNG(kreditkarte, native = TRUE)
img2 <- readPNG(zahnbuerste, native = TRUE)
img3 <- readPNG(creme, native = TRUE)
img4 <- readPNG(butter, native = TRUE)
  
# bilder zum plot hinzufügen  
img_graph <- EinstiegsPlot +                  
  inset_element(p = img1,
                left = 0.02,
                bottom = 0.09,
                right = 0.08,
                top = 0.3) + 
  inset_element(p = img2,
                left = 0.08,
                bottom = 0.17,
                right = 0.17,
                top = 0.3) +
  inset_element(p = img3,
                left = 0.3,
                bottom = 0.5,
                right = 0.5,
                top = 0.7) +
  inset_element(p = img4,
                left = 0.7,
                bottom = 0.87,
                right = 0.85,
                top = 0.98) 

girafe(
  ggobj = img_graph,
  width_svg = 7,
  height_svg = 7*0.618,
    options = list(
    opts_tooltip(css = "background: #00868B; color: #FFFFFF;padding:2px;border-radius:2px;")))

```

# Wie hat sich die globale Plastikproduktion innerhalb der letzten Jahre entwickelt?
 
```{r}
global_plastic %>%
 mutate(gpp = as.numeric(gpp)/1000000) %>%
ggplot(aes(x = Year, y = gpp )) + geom_line(color = '#00868B', alpha = 0.6) + geom_point_interactive(aes(data_id = gpp, tooltip = gpp), color = '#00868B') +
  scale_x_continuous(limits = c(1950, 2015), breaks = c(1950, 1960, 1970, 1980, 1990, 2000, 2010, 2015), expand = c(0.02,0.02)) +
  scale_y_continuous(limits = c(0, 400), breaks = c(0, 50, 100, 150, 200, 250, 300, 350, 400), expand = c(0,0)) +
  labs(x = "", y = "Plastik in Millionen Tonnen", title = "Im Vergleich zu 1950 hat sich 2015 die jährliche\n Plastikproduktion fast um das 200-fache erhöht", subtitle = "Globale Entwicklung der Plastikproduktion in Millionen Tonnen von 1950 bis 2015") +
  theme_minimal_hgrid(12) -> plot_global_plastic

girafe(
  ggobj = plot_global_plastic,
  width_svg = 7,
  height_svg = 7*0.618,
    options = list(
    opts_tooltip(css = "background: #00868B; color: #FFFFFF;padding:2px;border-radius:2px;")))
```

```{r}
cumulative_global_plastic %>%
  rename(cgpp = `Cumulative global plastics production (million tonnes)`) %>%
 mutate(cgpp = as.numeric(cgpp)/1000000000) %>%
ggplot(aes(x = Year, y = cgpp )) + geom_area(fill = '#00868B', alpha= 0.6) + geom_point_interactive(aes(data_id = cgpp, tooltip = cgpp), color = '#00868B') +
  scale_x_continuous(limits = c(1950, 2015), breaks = c(1950, 1960, 1970, 1980, 1990, 2000, 2010, 2015), expand = c(0.02, 0.02)) +
  scale_y_continuous(limits = c(0, 8), breaks = c(0, 1, 2, 3, 4, 5, 6, 7, 8), expand = c(0,0)) +
  labs(x = "", y = "Plastik in Milliarden Tonnen", title = "Mehr als die Hälfte des weltweit produzierten Plastiks\n wurde in den letzten 15 Jahren* produziert", subtitle = "Kumulation  der globalen Plastikproduktion von 1950 bis 2015" ) +
  theme_minimal_hgrid(12) -> plot_cumulative_global_plastic

girafe(
  ggobj = plot_cumulative_global_plastic,
  width_svg = 7,
  height_svg = 7*0.618,
    options = list(
    opts_tooltip(css = "background: #00868B; color: #FFFF; padding:2px;border-radius:2px;")))
```

# Wie sieht das ganze im Ländervergleich aus?

```{r}
#Platzhalter, Chunk für Weltkarte
```

# Abfallaufkommen in Deutschland 

```{r}
#Lollipop-Plot
ggplot(PlastikinMillTonnen, aes(x= Jahre, y= MillTonnen)) +
   geom_segment( aes(x= Jahre, xend=Jahre, y= 0, yend= MillTonnen), alpha =0.2) +
  geom_point_interactive (aes (tooltip = MillTonnen, data_id = MillTonnen), size=5, color="#00868B", alpha = 0.7) +
   scale_x_continuous(breaks = c(2004,2006,2008,2010,2012,2014,2016,2018))+
  scale_y_continuous(limits = c(0, 3.5), expand = c(0,0)) +
  labs(title = "Aufkommen von Plastikabfall in Deutschland", subtitle = "Plastikabfall von 2004 bis 2018 in Millionen Tonnen", y= "Millionen Tonnen") +
  theme_minimal_hgrid() +
  theme(axis.title.x=element_blank()) -> Plot2

girafe(
  ggobj = Plot2,
  width_svg = 7,
  height_svg = 7*0.618,
    options = list(
    opts_tooltip(css = "background: #00868B; color: #FFFF; padding:2px;border-radius:2px;")))
```

# Was passiert mit dem ganzen Plastikmüll?

```{r}
global_plastic_fate %>%
group_by(Entity) %>%
ggplot(aes(x = Year, y = `Estimated historic plastic fate`, color= Entity)) +
 geom_point()+
 scale_x_continuous(limits = c(1980, 2015), breaks = c(1980, 1990, 2000, 2010, 2015), expand = c(0.02,0.02))+
  scale_y_continuous(expand = c(0.02,0)) +
  labs(x= "", y= "prozentualer Anteil", title= "Globaler Kunststoffabfall differnziert nach Entsorgungsart, 1980 bis 2015")+
  scale_colour_discrete(name= "Entsorgungsart", breaks=c("Discarded", "Incinerated", "Recycled"),labels= c("Entsorgung (auf Mülldeponien)", "Verbrennung", "Recyceln"))+
  theme_minimal_hgrid(12)
```

# Zusammenhang Wohlstand und Plastik

```{r}
mydata2 %>%
  ggplot(aes(x = `Per capita plastic waste (g/person/day)`, y = `Per capita mismanaged plastic waste`, size = BIP, fill = Kontinent)) + geom_point_interactive(position = "jitter", shape = 21, color = "black", aes(data_id = Entity, tooltip = Entity)) + 
  scale_x_continuous(limits = c(0, 700), breaks = c(0, 100, 200, 300, 400, 500, 600, 700)) +
  scale_y_continuous(limits = c(0, 300), breaks = c(0, 50, 100, 150, 200, 250, 300)) +
  theme_minimal_grid() +
  theme(axis.text.y = element_text(vjust = 0)) +
  scale_fill_brewer(palette = "Set2") +
  labs(x = "Plastikmüllproduktion pro Kopf (täglich in g)", y = "Inadäquat entsorgter Plastikmüll pro Kopf (täglich in g)", title = "Problematisch ist die Mischung aus hoher Plastikproduktion in\n wohlhabenderen und inadäquater Entsorgung in ärmeren Ländern ", subtitle = "Zusammenhang von Wohlstand, Plastikmüllproduktion und inadäquater Entsorgung") +
  scale_size(range=c(1,8), breaks=c(25000,50000,75000,100000),labels=c("25.000$","50.000$","75.000$","100.000$"),guide="legend") +
  annotate(geom = "label", label= "Deutschland", x= 490, y= 25) -> plot_per_capita_waste_mismanagement_GDP


girafe(
  ggobj = plot_per_capita_waste_mismanagement_GDP,
  width_svg = 9,
  height_svg = 9*0.618,
    options = list(
    opts_tooltip(opacity = .7, css = "background: #00868B; color: #FFFF; padding:2px;border-radius:2px;"),
    opts_hover(css = "fill: #00868B;"),
    opts_hover_inv(css = "opacity: 0.4;")))
```

